<?php

namespace DoctrineProxies\__CG__\Amulet\Entity\Options;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WarStats extends \Amulet\Entity\Options\WarStats implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Amulet\\Entity\\Options\\WarStats' . "\0" . 'id', '' . "\0" . 'Amulet\\Entity\\Options\\WarStats' . "\0" . 'attack', '' . "\0" . 'Amulet\\Entity\\Options\\WarStats' . "\0" . 'accuracy', '' . "\0" . 'Amulet\\Entity\\Options\\WarStats' . "\0" . 'crit_rate', '' . "\0" . 'Amulet\\Entity\\Options\\WarStats' . "\0" . 'attack_speed', '' . "\0" . 'Amulet\\Entity\\Options\\WarStats' . "\0" . 'magic_boost', '' . "\0" . 'Amulet\\Entity\\Options\\WarStats' . "\0" . 'magic_accuracy', '' . "\0" . 'Amulet\\Entity\\Options\\WarStats' . "\0" . 'speed');
        }

        return array('__isInitialized__', '' . "\0" . 'Amulet\\Entity\\Options\\WarStats' . "\0" . 'id', '' . "\0" . 'Amulet\\Entity\\Options\\WarStats' . "\0" . 'attack', '' . "\0" . 'Amulet\\Entity\\Options\\WarStats' . "\0" . 'accuracy', '' . "\0" . 'Amulet\\Entity\\Options\\WarStats' . "\0" . 'crit_rate', '' . "\0" . 'Amulet\\Entity\\Options\\WarStats' . "\0" . 'attack_speed', '' . "\0" . 'Amulet\\Entity\\Options\\WarStats' . "\0" . 'magic_boost', '' . "\0" . 'Amulet\\Entity\\Options\\WarStats' . "\0" . 'magic_accuracy', '' . "\0" . 'Amulet\\Entity\\Options\\WarStats' . "\0" . 'speed');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WarStats $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttack($attack)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttack', array($attack));

        return parent::setAttack($attack);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttack()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttack', array());

        return parent::getAttack();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccuracy($accuracy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccuracy', array($accuracy));

        return parent::setAccuracy($accuracy);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccuracy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccuracy', array());

        return parent::getAccuracy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCritRate($critRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCritRate', array($critRate));

        return parent::setCritRate($critRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCritRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCritRate', array());

        return parent::getCritRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttackSpeed($attackSpeed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttackSpeed', array($attackSpeed));

        return parent::setAttackSpeed($attackSpeed);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttackSpeed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttackSpeed', array());

        return parent::getAttackSpeed();
    }

    /**
     * {@inheritDoc}
     */
    public function setMagicBoost($magicBoost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMagicBoost', array($magicBoost));

        return parent::setMagicBoost($magicBoost);
    }

    /**
     * {@inheritDoc}
     */
    public function getMagicBoost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMagicBoost', array());

        return parent::getMagicBoost();
    }

    /**
     * {@inheritDoc}
     */
    public function setMagicAccuracy($magicAccuracy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMagicAccuracy', array($magicAccuracy));

        return parent::setMagicAccuracy($magicAccuracy);
    }

    /**
     * {@inheritDoc}
     */
    public function getMagicAccuracy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMagicAccuracy', array());

        return parent::getMagicAccuracy();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpeed($speed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpeed', array($speed));

        return parent::setSpeed($speed);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpeed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpeed', array());

        return parent::getSpeed();
    }

}
