# Created by PhpStorm
# File: routes
# Author: Maks Babenko <mbabenko21@gmail.com>
# Date: 11.05.14 - 18:19

home:
  path: "/"
  defaults: { _controller: "AmuletOfDragon\\Controller\\HomeController::indexAction" }

login:
  path: "/login{ext}"
  defaults: { _controller: "AmuletOfDragon\\Controller\\AuthController::loginAction", ext: ".html"}
  requirements:
    ext: ".html|.php"

test_action:
  path: "/user/{id}"
  defaults: { _controller: "AmuletOfDragon\\Controller\\HomeController::testAction"}
  requirements:
    ext: ".html|.php"